### ISSUE TITLE
Seg Fault on compile

### ISSUE THREAD

**Issue by BrianBock** [wol101/GaitSym_2017#1]
Hi! I just discovered this project and I think it looks really cool. I wanted to play around with it a bit. I cloned the directory and ran 'make' in terminal (Mac OSX 10.14.2). After several minutes, it created a 'bin' folder with gaitsym as an executable. I tried launching gaitsym and got "Segmentation fault: 11"

**Comment by wol101** [comment]
Sadly my Mac support options ar every limited. I can only compile 2017 on Windows currently.
