### ISSUE TITLE
Correct build procedure?

### ISSUE THREAD

**Issue by lennonab** [wol101/GaitSym_2017#2]
Dear Prof. Sellers, 

I wonder if you could provide some overview of the required/recommended build process for your GaitSym software. I'm running Ubuntu Linux 18.04 with gcc 7.4.0 and Qt 5.12.4 (64 bit). Below is a description of what I've tried to date.

I've managed to build the console executable (bin/gaitsym etc.) using the makefile in the root of the folder.  I don't have a model to test this, however, as the links on the www.animalsimulation.org site seem to be broken.  I tried a model from the 2019 repository but this seemed to have some incompatibilities that I wouldn't know where to start with --- I am unfamiliar with your XML format  and a facile change from GaitSym2019 to 2017 in the root node didn't do the trick unfortunately.

I've also tried to build the GUI using Qt Creator and the supplied GaitSym2017.pro file but have run in to some issues there as well.

First, the Irrlicht library threw an error due to strict ANSI checking.  I got past this by disabling this in the compliler flag in the QMAKE_CXXFLAGS with -U__STRICT_ANSI__

The error I have not been able to overcome is an apparently missing file in the GaitSymQt folder called "Settings.h" --- this seems to be needed by "Preferences.cpp" and "MainWindow.cpp" in the GaitSymQt folder.  I've tried looking in some of the other version repositories for this file but can't seem to find it.  Is it possible that the original commit neglected to include this file? If there is a different version I should be compiling then please let me know which one --- I've already tried 2019 but had even less success with it, although I did get the console application to compile after manually adding the pystring library, which was missing from the 2019 repo.

Any help would be much appreciated.  I am very interested to try out this software for a student I am supervising who is trying to reconstruct gait of physically impaired individuals whose remains have been recovered from medieval archaeological sites. 

Kind regards,
Alex Lennon
Queen's University Belfast

**Comment by wol101** [comment]
If you need Ubuntu support then I would go with 2019 unless you really need to use 2017 models. 2017 is being maintained on Windows but it was never properly built on Ubuntu, whereas Ubuntu is a test platform for 2019 (but most of the issues with Ubuntu are getting all the bits of Qt installed properly).
